# Generated by Django 5.0.6 on 2024-06-05 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000)),
                ('time', models.TimeField(default=datetime.time(20, 10, 24, 832291))),
                ('user', models.CharField(max_length=200)),
                ('room_id', models.CharField(max_length=200)),
            ],
        ),
    ]
